name: tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
     

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, warp-ubuntu-latest-x64-4x, warp-ubuntu-latest-x64-8x]
        php: [8.1, 8.2, 8.3]
        laravel: [10, 11]
        exclude:
          - php: 8.1
            laravel: 11

    runs-on: ${{matrix.os}}
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Runner ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, bcmath
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none
        env:
          runner: self-hosted

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
